services:
  - type: web
    name: hello-dreams-ai-api
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm run migration:run:prod
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: hello-dreams-ai-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: hello-dreams-ai-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: hello-dreams-ai-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: hello-dreams-ai-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: hello-dreams-ai-db
          property: database
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 24h
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ORIGINAL_HEADSHOT_BUCKET
        value: headshot-originals
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_IMAGE_EDIT_MODEL
        value: dall-e-2
      - key: GEMINI_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_PLAN_CODE
        sync: false
      - key: CREDITS_PER_PAYMENT
        value: "1000"
      - key: CREDITS_PER_SUBSCRIPTION
        value: "10000"
      - key: NGN_TO_USD_RATE
        value: "1500"

databases:
  - name: hello-dreams-ai-db
    plan: free
    databaseName: hello_dreams_ai
    user: hello_dreams_ai_user
